project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog - Lukka Wolff"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lawolff1702
      - icon: linkedin
        href: https://www.linkedin.com/in/lukka-wolff/

format:
  html:
    title-block-banner: false
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





